version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: buzz
      POSTGRES_PASSWORD: buzz
      POSTGRES_DB: buzz_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5555:5432

volumes:
  postgres_data:
